---
name: Makefile CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with docker
      uses: addnab/docker-run-action@v3
      with:
        image: debian:bookworm-slim
        options: -v ${{ github.workspace }}:/github/workspace -w /github/workspace
        run: |
          apt update
          apt install --no-install-recommends -y golang ca-certificates curl fakeroot build-essential debhelper
          fakeroot debian/rules binary
          ls .
          ls ..

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ../findmydeviceserver_${{ github.ref_name }}-1_amd64.deb
