---
name: Makefile CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with docker
      uses: addnab/docker-run-action@v3
      with:
        image: debian:bookworm-slim
        options: -v ${{ github.workspace }}:/github/workspace -w /github/workspace
        run: |
          echo 'deb http://mirror.yandex.ru/debian/ bookworm-backports main contrib non-free non-free-firmware' > /etc/apt/sources.list.d/backports.list
          apt-get update
          apt-get install --no-install-recommends -y -t bookworm-backports golang ca-certificates curl fakeroot build-essential debhelper
          VERSION=${{ github.ref_name }} fakeroot debian/rules binary
          mv ../findmydeviceserver_${{ github.ref_name }}-1_amd64.deb .

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: findmydeviceserver_${{ github.ref_name }}-1_amd64.deb
        body_path: ${{ github.workspace }}/debian/changelog
